version: '3.5'

services:
  server-app:
    build: .
    restart: always
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_PORT: 3306
      DB_PASSWORD: rootrootroot
      DB_NAME: crypto_app_dev
      RAILS_MAX_THREADS: 20
    volumes:
      - .:/usr/src/crypto_app
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootrootroot
#    ports:
#      - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume: